site_name: MkDocs Test
theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'purple'
  logo:
    icon: 'help'
  favicon: 'assets/images/favicon.ico'
repo_name: 'Kore-Development/mkdocs-test'
repo_url: 'https://github.com/Kore-Development/mkdocs-test'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
